version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always
  backend-tests:
    build:
      context: ./backend
    command: pytest --maxfail=1 --disable-warnings -q  # Запускает тесты


  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    restart: always
