version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    restart: always
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:~/devops_project/backend/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

